# Generated by Django 5.1.7 on 2025-03-31 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotel_comment'),
        ('restaurants', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_comments', to='hotels.hotel'),
        ),
    ]
