# Generated by Django 5.1.7 on 2025-03-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('restaurants', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurants.comment'),
        ),
    ]
