# Generated by Django 5.1.7 on 2025-03-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='comment',
        ),
    ]
