# Generated by Django 5.1.7 on 2025-03-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historical_places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplace',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_places', to='historical_places.country'),
        ),
        migrations.AddField(
            model_name='historicalfavourite',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_favourites', to='historical_places.historicalplace'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='historical_places.country'),
        ),
        migrations.AddField(
            model_name='historicalplace',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_places', to='historical_places.region'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalfavourite',
            unique_together={('user', 'place')},
        ),
    ]
