# Generated by Django 5.1.7 on 2025-03-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_code',
            new_name='verification_code',
        ),
    ]
