# Generated by Django 5.1.6 on 2025-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='historical_places/photos/'),
        ),
    ]
