# Generated by Django 5.1.6 on 2025-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_places', '0002_alter_historicalplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='entry_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
