# Generated by Django 5.1.6 on 2025-03-13 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_places', '0003_historicalplace_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_places', to='historical_places.country'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_places', to='historical_places.region'),
        ),
    ]
