# Generated by Django 5.1.6 on 2025-03-09 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historical_places', '0002_alter_historicalplace_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rest_places/photos/')),
                ('stars', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_places', to='historical_places.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_places', to='historical_places.region')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_favourites', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_favourites', to='rest_place.restplace')),
            ],
            options={
                'unique_together': {('user', 'place')},
            },
        ),
    ]
