# Generated by Django 5.1.6 on 2025-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restplace',
            name='entry_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
